# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculadora.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'calculadora.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63\x61lculadora.proto\"+\n\x13OperacaoDoisNumeros\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\"\x1d\n\x10OperacaoUmNumero\x12\t\n\x01\x61\x18\x01 \x01(\x01\"\x1e\n\tResultado\x12\x11\n\tresultado\x18\x01 \x01(\x01\x32\xa4\x02\n\x0b\x43\x61lculadora\x12)\n\x05Somar\x12\x14.OperacaoDoisNumeros\x1a\n.Resultado\x12,\n\x08Subtrair\x12\x14.OperacaoDoisNumeros\x1a\n.Resultado\x12/\n\x0bMultiplicar\x12\x14.OperacaoDoisNumeros\x1a\n.Resultado\x12+\n\x07\x44ividir\x12\x14.OperacaoDoisNumeros\x1a\n.Resultado\x12-\n\x0cRaizQuadrada\x12\x11.OperacaoUmNumero\x1a\n.Resultado\x12/\n\x0b\x45xponenciar\x12\x14.OperacaoDoisNumeros\x1a\n.Resultadob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculadora_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPERACAODOISNUMEROS']._serialized_start=21
  _globals['_OPERACAODOISNUMEROS']._serialized_end=64
  _globals['_OPERACAOUMNUMERO']._serialized_start=66
  _globals['_OPERACAOUMNUMERO']._serialized_end=95
  _globals['_RESULTADO']._serialized_start=97
  _globals['_RESULTADO']._serialized_end=127
  _globals['_CALCULADORA']._serialized_start=130
  _globals['_CALCULADORA']._serialized_end=422
# @@protoc_insertion_point(module_scope)
